"""Darwinian Memory Agent (DMSA) — v3 AndroidWorld Agent.

A Planner-Actor-Memory-Verifier agent that wraps the Darwinian Memory
System (arXiv:2601.22528) around an M3A-style action executor.

Architecture
------------
    DMSAgent (EnvironmentInteractingAgent)
    ├── Planner LLM callback → decomposes goal into Plan(precondition, goal)
    ├── M3A Actor → executes one action per step(), accumulating trajectory
    ├── MemoryBank → dual-factor retrieval, ϵ-mutation, risk gating
    ├── K-Verifier (K=3) → guards memory reliability
    ├── Self-Regulation → Survival-Value driven Elbow Method pruning
    └── Bayesian Risk Assessment → LCL risk score + dynamic thresholding

The agent is fully training-free — it adds evolutionary memory on top of
any MLLM without modifying model weights.
"""

from __future__ import annotations

import copy
import json
import os
import sys
import time
from typing import Any, Callable, Optional

import numpy as np
from PIL import Image

from absl import logging

from android_world.agents import agent_utils
from android_world.agents import base_agent
from android_world.agents import dms_utils
from android_world.agents import infer
from android_world.agents import m3a as m3a_lib
from android_world.agents import m3a_utils
from android_world.env import interface
from android_world.env import json_action
from android_world.env import representation_utils

# Add the repo root so that "from others.darwinian_memory import ..." works.
_repo_root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
if _repo_root not in sys.path:
  sys.path.insert(0, _repo_root)

from others.darwinian_memory.config import DMSConfig
from others.darwinian_memory.dms import DMS, TaskResult
from others.darwinian_memory.memory_bank import MemoryBank, RetrievalResult
from others.darwinian_memory.memory_entry import MemoryEntry, Plan, ObsAct
from others.darwinian_memory.risk import (
    BayesianStats,
    compute_risk_score,
    compute_dynamic_threshold,
    compute_global_failure_rate,
)
from others.darwinian_memory.verifier import (
    KVerifier,
    VerificationResult,
    VERIFIER_SYSTEM_PROMPT,
)


# ── DMSA-specific Plan type ────────────────────────────────────────────


class AgentAct:
  """An action generated by the Agent LLA within a sub-plan step."""

  def __init__(
      self,
      action_type: str = '',
      index: Optional[int] = None,
      text: str = '',
      direction: str = '',
      goal_status: str = '',
      app_name: str = '',
  ):
    self.action_type = action_type
    self.index = index
    self.text = text
    self.direction = direction
    self.goal_status = goal_status
    self.app_name = app_name

  def to_json_action(self) -> json_action.JSONAction:
    return json_action.JSONAction(
        action_type=self.action_type,
        index=self.index,
        x=None,
        y=None,
        text=self.text,
        direction=self.direction,
        goal_status=self.goal_status,
        app_name=self.app_name,
    )

  def __repr__(self) -> str:
    return (
        f"AgentAct({self.action_type}"
        + (f", index={self.index}" if self.index is not None else '')
        + (f", text={self.text!r}" if self.text else '')
        + (f", direction={self.direction!r}" if self.direction else '')
        + ')'
    )


# ── DMSAgent ───────────────────────────────────────────────────────────


class DMSAgent(base_agent.EnvironmentInteractingAgent):
  """v3 agent: Darwinian Memory System integrated with M3A action executor.

  Usage
  -----
      env = env_launcher.load_and_setup_env(...)
      llm = infer.Gpt4Wrapper('gpt-4-turbo-2024-04-09')
      agent = DMSAgent(env, llm, dms_config=DMSConfig())
      agent.step("Turn off WiFi")
  """

  def __init__(
      self,
      env: interface.AsyncEnv,
      llm: infer.MultimodalLlmWrapper,
      name: str = 'DMSA',
      wait_after_action_seconds: float = 0.3,
      dms_config: Optional[DMSConfig] = None,
      memory_persistence_dir: str = '',
      screenshot_scale: float = 0.5,
  ):
    """Initializes the DMS Agent.

    Args:
      env: The Android environment.
      llm: The multimodal LLM wrapper (shared by Planner, Actor, Verifier).
      name: Agent name.
      wait_after_action_seconds: Pause after each action for screen stabilization.
      dms_config: DMS hyperparameters.  Uses paper defaults if None.
      memory_persistence_dir: If set, loads/saves memory bank from this directory.
    """
    super().__init__(env, name)
    self.llm = llm
    self.wait_after_action_seconds = wait_after_action_seconds
    self.transition_pause = 0.3
    self.screenshot_scale = screenshot_scale

    # ── DMS Core ──────────────────────────────────────────────────
    self._dms_config = dms_config or DMSConfig()
    self._dms = DMS(config=self._dms_config)

    # Try to initialize embedding (non-critical — falls back to TF-IDF)
    try:
      self._dms.initialize_embedding()
    except Exception as e:
      logging.warning('DMS embedding init failed (will use TF-IDF fallback): %s', e)
      self._dms.initialize_embedding(
          corpus_texts=['placeholder text for TF-IDF vocabulary build']
      )

    # Register Planner, Actor, Verifier callbacks
    self._dms.set_planner(self._planner_callback)
    self._dms.set_actor(self._actor_callback)
    self._dms.set_verifier(self._verifier_callback)

    # ── Persistence ────────────────────────────────────────────────
    self._memory_persistence_dir = memory_persistence_dir
    if memory_persistence_dir:
      self._bank_path = os.path.join(memory_persistence_dir, 'dms_bank.json')
      if os.path.exists(self._bank_path):
        try:
          self._dms.bank = MemoryBank.load(self._bank_path, self._dms_config)
          logging.info(
              'Loaded DMS memory bank (%d entries) from %s',
              self._dms.bank.size,
              self._bank_path,
          )
        except Exception as e:
          logging.warning('Failed to load memory bank: %s', e)

    # ── Per-task state (re-initialized on reset()) ─────────────────
    self._overall_goal: str = ''
    self._sub_plans: list[Plan] = []
    self._current_plan_idx: int = 0
    self._sub_plan_history: list[dict[str, Any]] = []
    self._sub_plan_trajectory: list[ObsAct] = []
    self._task_memories: list[MemoryEntry] = []
    self._planner_called_for_task: bool = False
    self._sub_plan_trajectory_offset: int = 0
    self._current_memory_entry: Optional[MemoryEntry] = None

    # ── Deterministic trajectory replay state (§3.2.2) ─────────────
    self._replay_active: bool = False
    self._replay_entry: Optional[MemoryEntry] = None
    self._replay_index: int = 0

  # ── Screenshot scaling ──────────────────────────────────────────────

  def _maybe_resize(self, img: np.ndarray) -> np.ndarray:
    """Downscale screenshot if screenshot_scale < 1.0."""
    if self.screenshot_scale >= 1.0:
      return img
    h, w = img.shape[:2]
    nw, nh = int(w * self.screenshot_scale), int(h * self.screenshot_scale)
    pil = Image.fromarray(img).resize((nw, nh), Image.LANCZOS)
    return np.array(pil)

  # ── Properties ──────────────────────────────────────────────────────

  @property
  def memory_bank(self) -> MemoryBank:
    return self._dms.bank

  @property
  def dms_config(self) -> DMSConfig:
    return self._dms_config

  # ── Lifecycle ───────────────────────────────────────────────────────

  def reset(self, go_home_on_reset: bool = False):
    super().reset(go_home_on_reset)
    self.env.hide_automation_ui()
    self._overall_goal = ''
    self._sub_plans = []
    self._current_plan_idx = 0
    self._sub_plan_history = []
    self._sub_plan_trajectory = []
    self._task_memories = []
    self._planner_called_for_task = False
    self._sub_plan_trajectory_offset = 0
    self._current_memory_entry = None
    self._replay_active = False
    self._replay_entry = None
    self._replay_index = 0

  # ── DMS Callbacks ───────────────────────────────────────────────────

  def _planner_callback(
      self, observation: Any, task_text: str, context: Any
  ) -> list[Plan]:
    """Planner callback — called by DMS to decompose a goal into sub-plans.

    In our adapted architecture, the Planner is called externally (in the
    first step() invocation) rather than by the DMS orchestrator.
    This callback is registered so that dms.run_task() would work,
    but in practice we invoke _run_planner() directly inside step().
    """
    del observation, context
    return self._run_planner(task_text)

  def _actor_callback(
      self, observation: Any, sub_task: Plan, context: Any
  ) -> list[ObsAct]:
    """Actor callback — the DMS expects the Actor to return a full trajectory.

    Since AndroidWorld's step-by-step paradigm requires per-action interaction,
    we do NOT use this callback during normal operation.  Instead, step()
    executes a single action and appends it to the trajectory.
    This callback exists for compatibility with dms.run_task().
    """
    del observation, sub_task, context
    return list(self._sub_plan_trajectory)

  def _verifier_callback(
      self,
      goal_text: str,
      execution_history: list[Any],
      final_screenshot: Any,
  ) -> VerificationResult:
    """Verifier callback — asks the LLM to judge whether the task succeeded."""
    return self._run_verifier(goal_text, execution_history, final_screenshot)

  # ── Planner ─────────────────────────────────────────────────────────

  def _run_planner(self, goal: str) -> list[Plan]:
    """Invoke the LLM to decompose `goal` into sub-plans."""
    prompt = (
        dms_utils.PLANNER_SYSTEM_PROMPT
        + f'\n\nUser goal: {goal}\n\nOutput the JSON array of sub-tasks:'
    )
    try:
      raw_output, _, _ = self.llm.predict_mm(prompt, [])
    except Exception as e:
      logging.warning('Planner LLM call failed: %s', e)
      return [Plan(precondition='Any state', goal=goal)]

    if not raw_output or raw_output == infer.ERROR_CALLING_LLM:
      logging.warning('Planner returned empty output, falling back to single-plan.')
      return [Plan(precondition='Any state', goal=goal)]

    plans = dms_utils.parse_planner_output(raw_output)
    if not plans:
      logging.warning(
          'Planner output could not be parsed, falling back to single-plan. '
          'Raw: %s',
          raw_output[:200],
      )
      return [Plan(precondition='Any state', goal=goal)]

    logging.info('Planner generated %d sub-plans for goal: %s', len(plans), goal)
    for i, p in enumerate(plans):
      logging.info('  Plan %d: pre=%s  goal=%s', i, p.precondition, p.goal)
    return plans

  # ── Actor (single-step, adapted for AndroidWorld's step() loop) ─────

  def _build_actor_prompt(
      self, overall_goal: str, sub_goal: str, ui_elements: str, memory_hint: str = ''
  ) -> str:
    """Build the prompt for a single action selection within a sub-plan."""
    history_lines = [
        f'Step {i + 1}- {step["summary"]}'
        for i, step in enumerate(self._sub_plan_history)
    ]
    return dms_utils.build_sub_plan_action_prompt(
        overall_goal=overall_goal,
        sub_goal=sub_goal,
        history=history_lines,
        ui_elements=ui_elements,
        memory_hint=memory_hint,
    )

  def _generate_single_action(
      self, prompt: str, screenshot: Any, som_screenshot: Any
  ) -> tuple[Optional[str], Optional[str], Optional[str], bool]:
    """Call the LLM to generate ONE action.  Returns (reason, action_json, raw_response, is_safe)."""
    try:
      action_output, is_safe, raw_response = self.llm.predict_mm(
          prompt,
          [screenshot, som_screenshot],
      )
    except Exception as e:
      logging.warning('Actor LLM call failed: %s', e)
      return None, None, None, False

    if is_safe is False:
      action_output = (
          f'Reason: {m3a_utils.TRIGGER_SAFETY_CLASSIFIER}\n'
          'Action: {"action_type": "status", "goal_status": "infeasible"}'
      )
    if not raw_response:
      raise RuntimeError('Error calling LLM in action selection phase.')

    reason, action_json = m3a_utils.parse_reason_action_output(action_output)
    return reason, action_json, raw_response, (is_safe is not False)

  # ── Verifier ────────────────────────────────────────────────────────

  def _run_verifier(
      self,
      goal_text: str,
      execution_history: list[Any],
      final_screenshot: Any,
  ) -> VerificationResult:
    """Ask the LLM to verify whether a sub-plan was completed successfully.

    Uses the paper's Figure 9 verifier prompt (VERIFIER_SYSTEM_PROMPT).
    """
    if not execution_history:
      return VerificationResult(False, 'Empty execution history')

    history_text = '\n'.join(
        f'Step {i}: {act}' for i, act in enumerate(execution_history)
    )
    prompt = (
        f'{VERIFIER_SYSTEM_PROMPT}\n\n'
        f'Original Goal: {goal_text}\n\n'
        f'Execution History:\n{history_text}\n\n'
        f'Analyze whether the goal was achieved.  Output JSON only.'
    )
    images = [final_screenshot] if final_screenshot is not None else []

    try:
      result_text, _, raw_response = self.llm.predict_mm(prompt, images)
    except Exception as e:
      logging.warning('Verifier LLM call failed: %s', e)
      return VerificationResult(False, f'Verifier error: {e}')

    if not raw_response or result_text == infer.ERROR_CALLING_LLM:
      return VerificationResult(False, 'Verifier LLM call returned empty')

    # Parse JSON
    try:
      match = __import__('re').search(
          r'\{[^}]*"verified_success"[^}]*\}', result_text
      )
      if match:
        data = json.loads(match.group())
        return VerificationResult(
            success=data.get('verified_success', False),
            reason=data.get('reason', ''),
        )
    except (json.JSONDecodeError, KeyError):
      pass

    # Heuristic fallback
    return VerificationResult(False, f'Could not parse verifier output: {result_text[:200]}')

  # ── Memory Helpers ──────────────────────────────────────────────────

  def _retrieve_memory(self, plan: Plan) -> RetrievalResult:
    """Retrieve the best-matching memory for a plan, considering risk & mutation."""
    T_global = self._dms._compute_T_global()
    return self._dms.bank.retrieve(
        plan,
        current_logical_time=self._dms._logical_time,
        T_global=T_global,
    )

  def _store_memory(self, plan: Plan, trajectory: list[ObsAct]):
    """Store a new sub-plan trajectory in the memory bank."""
    if len(trajectory) <= 1:
      return  # §3.2.1: filter atomic actions
    entry = self._dms.bank.add(plan, trajectory)
    if entry is not None:
      self._task_memories.append(entry)

  def _finalize_sub_plan(self, success: bool):
    """Called when a sub-plan is finished (either success, infeasible, or step-limit).

    Updates the active memories list for global feedback regulation,
    and performs verification + memory storage if the sub-plan produced a trajectory.
    """
    if not self._sub_plan_trajectory:
      return

    current_plan = (
        self._sub_plans[self._current_plan_idx]
        if self._current_plan_idx < len(self._sub_plans)
        else None
    )

    if current_plan is not None and len(self._sub_plan_trajectory) > 1:
      if success:
        if self._current_memory_entry is not None:
          # Memory reuse succeeded — update metadata on the existing entry
          entry = self._current_memory_entry
          entry.meta.reuse_count += 1
          entry.meta.success_count += 1
          entry.meta.last_used_at = time.time()
          entry.meta.last_logical_time = self._dms._logical_time
          self._task_memories.append(entry)
        else:
          # Fresh exploration success — create new memory entry
          self._store_memory(current_plan, list(self._sub_plan_trajectory))
        stats = self._dms._get_or_create_plan_stats(current_plan)
        stats.successes += 1
      else:
        if self._current_memory_entry is not None:
          # Memory reuse failed — penalize
          should_prune = self._dms._kverifier.record_failure(
              self._current_memory_entry
          )
          self._current_memory_entry.meta.failure_count += 1
          if should_prune:
            self._dms.bank._remove_entry(self._current_memory_entry)
          else:
            self._task_memories.append(self._current_memory_entry)
        stats = self._dms._get_or_create_plan_stats(current_plan)
        stats.failures += 1

    self._current_memory_entry = None

    # Advance logical time
    self._dms._logical_time += 1
    self._dms.bank.advance_time(1)

    # Reset sub-plan state
    self._sub_plan_trajectory = []
    self._sub_plan_history = []
    self._sub_plan_trajectory_offset = 0
    self._current_plan_idx += 1

  # ── Deterministic Trajectory Replay (§3.2.2) ──────────────────────────

  def _resolve_action_target(
      self,
      action: json_action.JSONAction,
      ui_elements: list[Any],
  ) -> json_action.JSONAction:
    """Rebind an action's index to the current screen's UI elements.

    The cached trajectory records the element index as it was on the
    original screen.  On replay we resolve that index against the current
    UI tree; if the element text/content-description still matches, the
    action is executed as-is.  If the index no longer points at the
    expected element, we fall back to a unique visible text match so the
    replay stays deterministic even after minor state perturbation.
    """
    if action.action_type not in (
        json_action.CLICK,
        json_action.DOUBLE_TAP,
        json_action.LONG_PRESS,
    ):
      return action
    if action.index is None:
      return action
    if action.index < 0 or action.index >= len(ui_elements):
      return action
    logical_screen_size = self.env.logical_screen_size
    original = ui_elements[action.index]
    if m3a_utils.validate_ui_element(original, logical_screen_size):
      return action
    text = getattr(original, 'text', None) or getattr(
        original, 'content_description', None
    )
    if not text:
      return action
    matches = [
        (i, e)
        for i, e in enumerate(ui_elements)
        if m3a_utils.validate_ui_element(e, logical_screen_size)
        and (getattr(e, 'text', None) or getattr(e, 'content_description', None))
        == text
    ]
    if len(matches) == 1:
      rebound = copy.deepcopy(action)
      rebound.index = matches[0][0]
      return rebound
    return action

  def _start_replay(
      self,
      current_plan: Plan,
      memory_entry: MemoryEntry,
  ) -> None:
    """Begin deterministic replay of a cached trajectory for a sub-plan."""
    # §3.2.2 decoupled storage: trajectories live on disk and are fetched
    # on a retrieval hit.  After a MemoryBank.load() the in-memory
    # entry.trajectory is empty (only the index is restored), so always
    # re-read the trajectory to guarantee a non-empty replay.
    trajectory = self._dms.bank._load_trajectory(memory_entry)
    if not trajectory:
      trajectory = list(memory_entry.trajectory)
    self._replay_active = True
    self._replay_entry = memory_entry
    self._replay_index = 0
    self._sub_plan_trajectory = trajectory
    logging.info(
        'DMSA — Replaying cached trajectory (%d steps) for sub-plan "%s"',
        len(self._sub_plan_trajectory),
        current_plan.goal[:60],
    )

  def _step_replay(
      self,
      current_plan: Plan,
      goal: str,
  ) -> base_agent.AgentInteractionResult:
    """Execute the next cached action in the replay loop.

    One cached action per agent.step() call (matching AndroidWorld's
    step-by-step interaction paradigm).  Returns done=True once the full
    trajectory has been replayed or a step fails.
    """
    step_data: dict[str, Any] = {
        'raw_screenshot': None,
        'before_screenshot_with_som': None,
        'before_ui_elements': [],
        'after_screenshot_with_som': None,
        'action_prompt': None,
        'action_output': None,
        'action_output_json': None,
        'action_reason': None,
        'action_raw_response': None,
        'summary_prompt': None,
        'summary': None,
        'summary_raw_response': None,
        'dms_memory_hit': True,
        'dms_memory_score': 0.0,
        'dms_sub_plan_idx': self._current_plan_idx,
        'dms_replayed': True,
    }
    if self._replay_entry is not None:
      step_data['dms_memory_id'] = self._replay_entry.memory_id

    trajectory = self._sub_plan_trajectory
    if self._replay_index >= len(trajectory):
      # Full trajectory replayed — sub-plan considered completed.
      self._replay_active = False
      self._replay_entry = None
      self._replay_index = 0
      step_data['summary'] = 'Replayed full trajectory; sub-task completed.'
      self._sub_plan_history.append(step_data)
      self._finalize_sub_plan(success=True)
      return self._step_result(
          step_data, self._current_plan_idx >= len(self._sub_plans)
      )

    obs_act = trajectory[self._replay_index]
    self._replay_index += 1
    action = obs_act.action
    if action is None:
      step_data['summary'] = 'Skipped replay step with no cached action.'
      self._sub_plan_history.append(step_data)
      return self._step_result(step_data, False)

    if not isinstance(action, json_action.JSONAction):
      action = (
          action.to_json_action()
          if isinstance(action, AgentAct)
          else json_action.JSONAction(
              **{
                  k: v
                  for k, v in vars(action).items()
                  if k in json_action.ACTION_KEYS
              }
          )
      )
    step_data['action_output_json'] = action

    if action.action_type == json_action.STATUS:
      if action.goal_status == 'infeasible':
        step_data['summary'] = 'Replayed memory declared the sub-task infeasible.'
        self._sub_plan_history.append(step_data)
        self._replay_active = False
        self._replay_entry = None
        self._replay_index = 0
        self._finalize_sub_plan(success=False)
        return self._step_result(
            step_data, self._current_plan_idx >= len(self._sub_plans)
        )
      step_data['summary'] = 'Replayed memory declared the sub-task completed.'
      self._sub_plan_history.append(step_data)
      self._replay_active = False
      self._replay_entry = None
      self._replay_index = 0
      self._finalize_sub_plan(success=True)
      return self._step_result(
          step_data, self._current_plan_idx >= len(self._sub_plans)
      )

    if action.action_type in (
        json_action.CLICK,
        json_action.DOUBLE_TAP,
        json_action.LONG_PRESS,
    ) and action.index is not None:
      try:
        state = self.get_post_transition_state()
        action = self._resolve_action_target(action, state.ui_elements)
      except Exception as e:
        logging.warning('DMSA replay — target resolution failed: %s', e)

    try:
      self.env.execute_action(action)
      time.sleep(self.wait_after_action_seconds)
    except Exception as e:
      logging.warning('DMSA [%s] — replay action failed: %s', goal, e)
      step_data['summary'] = f'Replay action failed: {e}'
      self._sub_plan_history.append(step_data)
      self._replay_active = False
      self._replay_entry = None
      self._replay_index = 0
      self._finalize_sub_plan(success=False)
      return self._step_result(step_data, False)

    remaining = len(trajectory) - self._replay_index
    step_data['summary'] = (
        f'Replayed step {self._replay_index}/{len(trajectory)}; '
        f'{remaining} remaining.'
    )
    self._sub_plan_history.append(step_data)
    return self._step_result(step_data, False)

  def _step_result(
      self,
      step_data: dict[str, Any],
      done: bool,
  ) -> base_agent.AgentInteractionResult:
    return base_agent.AgentInteractionResult(done, step_data)

  # ── Main step() — the AndroidWorld interface ─────────────────────────

  def step(self, goal: str) -> base_agent.AgentInteractionResult:
    """Execute one interaction step, guided by DMS memory.

    On the first call for a task:
      1. Planner decomposes goal into sub-plans
      2. First sub-plan is selected; memory is checked for reuse

    On subsequent calls:
      1. Continue executing the current sub-plan
      2. When sub-plan completes, move to the next one
      3. When all sub-plans complete, the task is done

    Returns:
      AgentInteractionResult with done=True when the task is finished.
    """
    step_data: dict[str, Any] = {
        'raw_screenshot': None,
        'before_screenshot_with_som': None,
        'before_ui_elements': [],
        'after_screenshot_with_som': None,
        'action_prompt': None,
        'action_output': None,
        'action_output_json': None,
        'action_reason': None,
        'action_raw_response': None,
        'summary_prompt': None,
        'summary': None,
        'summary_raw_response': None,
        'dms_memory_hit': False,
        'dms_memory_score': 0.0,
        'dms_sub_plan_idx': self._current_plan_idx,
    }

    # ── First call for this task: run Planner ──────────────────────
    if not self._planner_called_for_task:
      self._planner_called_for_task = True
      self._overall_goal = goal
      self._sub_plans = self._run_planner(goal)
      self._current_plan_idx = 0
      self._sub_plan_history = []
      self._sub_plan_trajectory = []
      self._task_memories = []
      self._sub_plan_trajectory_offset = 0
      self._dms._active_memories = []

      logging.info(
          'DMSA [%s] — Planner produced %d sub-plans',
          goal,
          len(self._sub_plans),
      )

    # Edge case: no sub-plans → report done
    if self._current_plan_idx >= len(self._sub_plans):
      step_data['summary'] = 'All sub-plans completed.'
      return base_agent.AgentInteractionResult(True, step_data)

    current_plan = self._sub_plans[self._current_plan_idx]

    # ── Active replay: execute next cached action (§3.2.2) ─────────
    if self._replay_active:
      return self._step_replay(current_plan, goal)

    # ── On the first step of a new sub-plan, check memory ─────────
    memory_hint = ''
    if self._sub_plan_trajectory_offset == 0:
      retrieval = self._retrieve_memory(current_plan)
      step_data['dms_memory_hit'] = False  # pyrefly: ignore[bad-assignment]
      step_data['dms_memory_score'] = retrieval.score  # pyrefly: ignore[bad-assignment]
      step_data['dms_risk_blocked'] = retrieval.risk_blocked  # pyrefly: ignore[bad-assignment]

      if retrieval.hit and not retrieval.risk_blocked and not retrieval.should_mutate:
        # MEMORY HIT: deterministically replay the cached trajectory.
        step_data['dms_memory_hit'] = True  # pyrefly: ignore[bad-assignment]
        entry = retrieval.entry
        if entry is not None:
          step_data['dms_memory_id'] = entry.memory_id  # pyrefly: ignore[bad-assignment]
          step_data['dms_memory_reuse_count'] = entry.meta.reuse_count  # pyrefly: ignore[bad-assignment]
          self._current_memory_entry = entry

          logging.info(
              'DMSA [%s] — Memory HIT for sub-plan "%s" (score=%.3f, reuse=%d), '
              'replaying %d cached actions',
              goal,
              current_plan.goal[:60],
              retrieval.score,
              entry.meta.reuse_count,
              len(entry.trajectory),
          )

          self._start_replay(current_plan, entry)
          return self._step_replay(current_plan, goal)
      else:
        if retrieval.risk_blocked:
          logging.info(
              'DMSA [%s] — Memory RISK-BLOCKED for sub-plan "%s"',
              goal,
              current_plan.goal[:60],
          )
        elif retrieval.should_mutate:
          logging.info(
              'DMSA [%s] — Memory ϵ-MUTATION triggered for sub-plan "%s"',
              goal,
              current_plan.goal[:60],
          )

    # ── MaxA guard: force-terminate sub-plan if step limit reached ─
    if self._sub_plan_trajectory_offset >= self._dms_config.MaxA:
      logging.warning(
          'DMSA [%s] — Sub-plan "%s" exceeded MaxA=%d, forcing termination.',
          goal,
          current_plan.goal[:60],
          self._dms_config.MaxA,
      )
      step_data['summary'] = (
          f'Sub-plan exceeded maximum steps ({self._dms_config.MaxA}).'
      )
      self._sub_plan_history.append(step_data)
      self._finalize_sub_plan(success=False)
      # Advance to next sub-plan if any, otherwise let episode_runner's
      # max_steps handle termination — don't declare done here.
      if self._current_plan_idx >= len(self._sub_plans):
        return base_agent.AgentInteractionResult(False, step_data)
      return base_agent.AgentInteractionResult(False, step_data)

    # ── Get current screen state ──────────────────────────────────
    state = self.get_post_transition_state()
    logical_screen_size = self.env.logical_screen_size
    orientation = self.env.orientation
    physical_frame_boundary = self.env.physical_frame_boundary

    before_ui_elements = state.ui_elements
    step_data['before_ui_elements'] = before_ui_elements
    before_ui_elements_list = m3a_lib._generate_ui_elements_description_list(
        before_ui_elements, logical_screen_size
    )

    step_data['raw_screenshot'] = state.pixels.copy()  # pyrefly: ignore[bad-assignment]
    before_screenshot = state.pixels.copy()
    for index, ui_element in enumerate(before_ui_elements):
      if m3a_utils.validate_ui_element(ui_element, logical_screen_size):
        m3a_utils.add_ui_element_mark(
            before_screenshot,
            ui_element,
            index,
            logical_screen_size,
            physical_frame_boundary,
            orientation,
        )
    step_data['before_screenshot_with_som'] = before_screenshot.copy()  # pyrefly: ignore[bad-assignment]

    # ── Build prompt and call LLM ─────────────────────────────────
    action_prompt = self._build_actor_prompt(
        goal, current_plan.goal, before_ui_elements_list, memory_hint
    )
    step_data['action_prompt'] = action_prompt  # pyrefly: ignore[bad-assignment]

    reason, action_json_str, raw_response, _ = self._generate_single_action(
        action_prompt,
        self._maybe_resize(state.pixels),
        self._maybe_resize(before_screenshot),
    )
    step_data['action_output'] = (  # pyrefly: ignore[bad-assignment]
        f'Reason: {reason}\nAction: {action_json_str}'
        if reason and action_json_str
        else None
    )
    step_data['action_raw_response'] = raw_response

    # ── Parse & validate action ───────────────────────────────────
    if (not reason) or (not action_json_str):
      logging.info('Action prompt output is not in the correct format.')
      step_data['summary'] = (
          'Output for action selection is not in the correct format.'
      )
      self._sub_plan_history.append(step_data)
      return base_agent.AgentInteractionResult(False, step_data)

    step_data['action_reason'] = reason  # pyrefly: ignore[bad-assignment]

    try:
      converted_action = json_action.JSONAction(
          **agent_utils.extract_json(action_json_str),  # pyrefly: ignore[bad-unpacking]
      )
      step_data['action_output_json'] = converted_action  # pyrefly: ignore[bad-assignment]
    except Exception as e:
      logging.info('Failed to convert output to valid action: %s', e)
      step_data['summary'] = (
          'Can not parse the output to a valid action. '
          'Please make sure to pick the action from the list with required '
          'parameters in the correct JSON format!'
      )
      self._sub_plan_history.append(step_data)
      return base_agent.AgentInteractionResult(False, step_data)

    # ── Validate index ────────────────────────────────────────────
    action_index_ = converted_action.index
    if (
        converted_action.action_type
        in ('click', 'long_press', 'input_text', 'scroll')
        and action_index_ is not None
        and action_index_ >= len(before_ui_elements)
    ):
      logging.info(
          'Index out of range: %d >= %d',
          action_index_,
          len(before_ui_elements),
      )
      step_data['summary'] = (
          'The parameter index is out of range. '
          'Remember the index must be in the UI element list!'
      )
      self._sub_plan_history.append(step_data)
      return base_agent.AgentInteractionResult(False, step_data)

    # ── Record trajectory entry (before execution) ─────────────────
    obs_act = ObsAct(
        observation=state.pixels.copy(),
        action=converted_action,
        step_index=self._sub_plan_trajectory_offset,
    )
    self._sub_plan_trajectory_offset += 1

    # ── Check for terminal actions ─────────────────────────────────
    if converted_action.action_type == 'status':
      if converted_action.goal_status == 'infeasible':
        logging.info('Agent declares task infeasible for sub-plan.')
      step_data['summary'] = 'Agent thinks the sub-task has been completed.'
      self._sub_plan_history.append(step_data)
      self._sub_plan_trajectory.append(obs_act)

      # Finalize this sub-plan
      self._finalize_sub_plan(
          success=(converted_action.goal_status != 'infeasible')
      )

      # Check if all sub-plans are done
      if self._current_plan_idx >= len(self._sub_plans):
        return base_agent.AgentInteractionResult(True, step_data)
      return base_agent.AgentInteractionResult(False, step_data)

    # ── Execute action on environment ──────────────────────────────
    if converted_action.action_type == 'answer':
      logging.info('Agent answered: %s', converted_action.text)

    try:
      self.env.execute_action(converted_action)
    except Exception as e:
      logging.info('Failed to execute action: %s', e)
      step_data['summary'] = (
          'Can not execute the action, make sure to select the action with '
          'the required parameters in the correct JSON format!'
      )
      self._sub_plan_history.append(step_data)
      self._sub_plan_trajectory.append(obs_act)
      return base_agent.AgentInteractionResult(False, step_data)

    time.sleep(self.wait_after_action_seconds)

    # ── After-action state capture ─────────────────────────────────
    after_state = self.env.get_state(wait_to_stabilize=False)
    after_ui_elements_list = m3a_lib._generate_ui_elements_description_list(
        after_state.ui_elements, logical_screen_size
    )
    after_screenshot = after_state.pixels.copy()
    for index, ui_element in enumerate(after_state.ui_elements):
      if m3a_utils.validate_ui_element(ui_element, logical_screen_size):
        m3a_utils.add_ui_element_mark(
            after_screenshot,
            ui_element,
            index,
            logical_screen_size,
            physical_frame_boundary,
            orientation,
        )

    m3a_utils.add_screenshot_label(step_data['before_screenshot_with_som'], 'before')
    m3a_utils.add_screenshot_label(after_screenshot, 'after')
    step_data['after_screenshot_with_som'] = after_screenshot.copy()

    # ── Summary generation ─────────────────────────────────────────
    summary_prompt = m3a_lib._summarize_prompt(
        action_json_str,
        reason,
        current_plan.goal,
        before_ui_elements_list,
        after_ui_elements_list,
    )
    step_data['summary_prompt'] = summary_prompt

    summary, is_safe, summary_raw = self.llm.predict_mm(
        summary_prompt,
        [
            self._maybe_resize(before_screenshot),
            self._maybe_resize(after_screenshot),
        ],
    )
    if is_safe is False:
      summary = 'Summary triggered LLM safety classifier.'
    if not summary_raw:
      step_data['summary'] = (
          f'Error calling LLM during summarization: {summary}'
      )
      self._sub_plan_history.append(step_data)
      self._sub_plan_trajectory.append(obs_act)
      return base_agent.AgentInteractionResult(False, step_data)

    step_data['summary'] = f'Action selected: {action_json_str}. {summary}'
    step_data['summary_raw_response'] = summary_raw
    logging.info('Summary: %s', summary)

    self._sub_plan_history.append(step_data)
    self._sub_plan_trajectory.append(obs_act)

    return base_agent.AgentInteractionResult(False, step_data)

  # ── Persistence ─────────────────────────────────────────────────────

  def save(self, path: Optional[str] = None):
    """Persist the DMS memory bank and plan stats to disk."""
    p = path or self._bank_path
    if not p:
      return
    self._dms.save(p)
    logging.info(
        'DMS memory saved to %s (%d entries)', p, self._dms.bank.size
    )

  def get_memory_stats(self) -> dict[str, Any]:
    """Return DMS memory and risk-tracking statistics."""
    bank_stats = self._dms.get_memory_stats()
    risk_report = self._dms.get_risk_report()
    return {
        'memory_bank': bank_stats,
        'risk_report': risk_report,
    }
